// <auto-generated />
using System;
using AppointmentScheduler.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppointmentScheduler.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240909182840_user_role_data_seed")]
    partial class user_role_data_seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppointmentScheduler.Domain.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("AppointmentScheduler.Domain.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("AppointmentScheduler.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d06e27e5-8dcf-4a80-92e4-fc9d257ec0a1"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("d85e26e5-7dcf-4a80-92e4-fc9d257ec0b2"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("AppointmentScheduler.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f3c447c-5283-4e13-8c44-2a0504ca7521"),
                            Cedula = "1152466496",
                            Name = "Luis Alejandro Pérez Abril",
                            RoleId = new Guid("d85e26e5-7dcf-4a80-92e4-fc9d257ec0b2")
                        },
                        new
                        {
                            Id = new Guid("f5d684d2-ed8f-467d-a835-2cb0067d4848"),
                            Cedula = "9396795",
                            Name = "Jose Eugenio Rodriguez",
                            RoleId = new Guid("d85e26e5-7dcf-4a80-92e4-fc9d257ec0b2")
                        },
                        new
                        {
                            Id = new Guid("a46e77a5-3924-414f-8507-b5635b4a7449"),
                            Cedula = "47438962",
                            Name = "Marta Alejandra Soacha",
                            RoleId = new Guid("d85e26e5-7dcf-4a80-92e4-fc9d257ec0b2")
                        },
                        new
                        {
                            Id = new Guid("43a13fae-d2e1-43f8-b774-7dd712777b95"),
                            Cedula = "987654321",
                            Name = "Elkin Dario Sanchez",
                            RoleId = new Guid("d06e27e5-8dcf-4a80-92e4-fc9d257ec0a1")
                        });
                });

            modelBuilder.Entity("AppointmentScheduler.Domain.Models.Appointment", b =>
                {
                    b.HasOne("AppointmentScheduler.Domain.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppointmentScheduler.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppointmentScheduler.Domain.Models.User", b =>
                {
                    b.HasOne("AppointmentScheduler.Domain.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
